/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/coin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials.NeonGlow} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Dark} />
      <group position={[0, -0.02, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Torus003.geometry} material={materials.Buildings} />
        <mesh geometry={nodes.Torus003_1.geometry} material={materials.NeonGlow} />
      </group>
    </group>
  )
}

useGLTF.preload('/coin-transformed.glb')
