/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 masked2.glb --transform --shadows -j -M -f 
Files: masked2.glb [4.31MB] > C:\Users\jkfro\Documents\Assets\Characters\masked\masked2-transformed.glb [468.37KB] (89%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/masked2-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Bone} />
        </group>
        <primitive object={nodes.neutral_bone} />
        <group name="Masked">
          <skinnedMesh name="Masked_1" geometry={nodes.Masked_1.geometry} material={materials.Material__37} skeleton={nodes.Masked_1.skeleton} />
          <skinnedMesh name="Masked_2" geometry={nodes.Masked_2.geometry} material={materials['skin.001']} skeleton={nodes.Masked_2.skeleton} />
          <skinnedMesh name="Masked_3" geometry={nodes.Masked_3.geometry} material={materials['Material.001']} skeleton={nodes.Masked_3.skeleton} />
          <skinnedMesh name="Masked_4" geometry={nodes.Masked_4.geometry} material={materials['Material.006']} skeleton={nodes.Masked_4.skeleton} />
          <skinnedMesh name="Masked_5" geometry={nodes.Masked_5.geometry} material={materials['Material.003']} skeleton={nodes.Masked_5.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/masked2-transformed.glb')
